### ISSUE TITLE
Hangs with '\' in html

### ISSUE THREAD

**Issue by Crotery** [ericclemmons/grunt-angular-templates#135] opened 2015-11-18 06:11 UTC
When tamplating a bunch of html files, this code just hangs the plugin:

```
 <span data-template="partials/directives/popup_template.html" data-content="{{role.desc || 'нет'}}" \
                          data-title="Описание" bs-popover data-trigger="hover" data-auto-close="true" data-placement="bottom"
                          style="cursor: pointer;">
                        {{role.ru}}
                    </span>
```
(please see the '\' symbol in the end of first line)

We had much problems with hanging builds in our CI server, but it (CI) allowed us to quickly find the reason for hanging.

(fails in 0.5.7)

**Comment by toupeira** [comment] 2015-11-18 17:38
Something similar with missing quotes on certain directive attributes:

```html
<div class="wrapper" translate-values="{}>
```

If I use `ng-class` instead I get a parse error after ~10 seconds. If I remove the `class` attribute the error appears immediately. With `translate-values` it hangs both with and without `class`. And by "hanging" I mean using 100% CPU, so there might be an error at some point in the far future :)

Also on 0.5.7, and NodeJS 4.2.2.

**Comment by hvdb** [comment] 2015-11-19 12:27
I also ran into the same issue and took a look at html-minifier, because that is where the problem is in.

What i see is that it tries to match a starttag but it ends up in a loop.

This is the regexp which causes the hang:
/^<([\w:-]+)((?:\s*[\w:.-]+(?:\s*(?:(?:=))\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/

And when the quote is not there or some other issue, the process just hangs.
Well i don't think it really hangs but it tries to find a match but that can take some time..

**Comment by toupeira** [comment] 2015-11-19 12:35
Yeah when I first stumbled over the issue it was hanging for several minutes before I lost interest, so I assume the time increases exponentially with the length/complexity of the template(s).

I guess http://stackoverflow.com/a/1732454/132312 is relevant here ;-)

**Comment by ericclemmons** [comment] 2015-11-25 17:30
I need help: #137.

**Comment by underscorebrody** [comment] 2016-02-16 13:01
I'm going to close this issue since we have no control over `html-minifier` (https://github.com/kangax/html-minifier), which is where the problem lies. We have added verbose logging so you should be able to see which template is causing the hang. I would also recommend that anyone running into trouble use an html linter as part of their build process (https://github.com/htmllint/grunt-htmllint).

**Closed by underscorebrody** 2016-02-16 13:01 UTC
